export default [
  {
    sysCode: '001',
    sysName: '系统资产编号',
    sysID: 1,
  }, {
    sysCode: '0002',
    sysName: '资产名称',
    sysID: 2,
  }, {
    sysCode: '0003',
    sysName: '存放地点',
    sysID: 3,
  }, {
    sysCode: '0004',
    sysName: '数量',
    sysID: 4,
  }, {
    sysCode: '0005',
    sysName: '库存状态',
    sysID: 5,
  }, {
    sysCode: '0006',
    sysName: '资产类别',
    sysID: 6,
  }, {
    sysCode: '0007',
    sysName: '品牌',
    sysID: 7,
  }, {
    sysCode: '0008',
    sysName: '型号',
    sysID: 8,
  }, {
    sysCode: '0009',
    sysName: '采购日期',
    sysID: 9,
  }, {
    sysCode: '0010',
    sysName: '使用部门',
    sysID: 10,
  }, {
    sysCode: '0011',
    sysName: '使用人员',
    sysID: 11,
  }, {
    sysCode: '0012',
    sysName: '资产用途',
    sysID: 12,
  }, {
    sysCode: '0013',
    sysName: '生产厂家',
    sysID: 13,
  }, {
    sysCode: '0014',
    sysName: '供应商',
    sysID: 14,
  }, {
    sysCode: '0015',
    sysName: '使用年限',
    sysID: 15,
  }, {
    sysCode: '0016',
    sysName: '备注',
    sysID: 16,
  }, {
    sysCode: '0017',
    sysName: '备注1',
    sysID: 17,
  }, {
    sysCode: '0018',
    sysName: '备注2',
    sysID: 18,
  }, {
    sysCode: '0019',
    sysName: '备注3',
    sysID: 19,
  }, {
    sysCode: '0020',
    sysName: '备注4',
    sysID: 20,
  }
];
