export default [
  {
    "DataSource": [
      {
        "ASSET_A2_AUTOID": 1,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": null,
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "固定资产",
        "ASSET_A2_20": "固定资产",
        "ASSET_A2_30": "固定资产",
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      },
      {
        "ASSET_A2_AUTOID": 2,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": null,
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "办公用品",
        "ASSET_A2_20": "001",
        "ASSET_A2_30": null,
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      },
      {
        "ASSET_A2_AUTOID": 3,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": "1",
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "房屋及建筑物",
        "ASSET_A2_20": "002",
        "ASSET_A2_30": null,
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      },
      {
        "ASSET_A2_AUTOID": 4,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": "1",
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "运输工具",
        "ASSET_A2_20": "003",
        "ASSET_A2_30": null,
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      },
      {
        "ASSET_A2_AUTOID": 6,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": "1",
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "办公家具",
        "ASSET_A2_20": "004",
        "ASSET_A2_30": null,
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      },
      {
        "ASSET_A2_AUTOID": 7,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": "1",
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "电器设备",
        "ASSET_A2_20": "005",
        "ASSET_A2_30": null,
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      },
      {
        "ASSET_A2_AUTOID": 8,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": "1",
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "硬件IT设备",
        "ASSET_A2_20": "006",
        "ASSET_A2_30": null,
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      },
      {
        "ASSET_A2_AUTOID": 9,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": "1",
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "低值资产",
        "ASSET_A2_20": "007",
        "ASSET_A2_30": null,
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      },
      {
        "ASSET_A2_AUTOID": 10,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": "2",
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "文具",
        "ASSET_A2_20": "008",
        "ASSET_A2_30": null,
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      },
      {
        "ASSET_A2_AUTOID": 11,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": "2",
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "电子用品",
        "ASSET_A2_20": "009",
        "ASSET_A2_30": null,
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      },
      {
        "ASSET_A2_AUTOID": 12,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": "2",
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "办公耗材",
        "ASSET_A2_20": "010",
        "ASSET_A2_30": null,
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      },
      {
        "ASSET_A2_AUTOID": 13,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": "2",
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "其他",
        "ASSET_A2_20": "012",
        "ASSET_A2_30": null,
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      },
      {
        "ASSET_A2_AUTOID": 14,
        "ASSET_A2_ISDEL": null,
        "ASSET_A2_MAKETIME": "2018-01-17",
        "ASSET_A2_MAKEUSER": null,
        "ASSET_A2_PARENTID": "10",
        "ASSET_A2_MAKEFROM": "1",
        "ASSET_A2_10": "铅笔橡皮",
        "ASSET_A2_20": "0501",
        "ASSET_A2_30": null,
        "ASSET_A2_40": null,
        "ASSET_A2_50": null,
        "ASSET_A2_60": null,
        "ASSET_A2_70": null
      }
    ],
    "codeId": "asset_a2",
    "DataValueField": "ASSET_A2_AUTOID",
    "DataTextField": "ASSET_A2_10",
    "TreeLevelField": "ASSET_A2_PARENTID"
  },
  {
    "DataSource": [
      {
        "System_4_10": 5,
        "System_4_20": "005001",
        "System_4_30": "005",
        "System_4_40": "新增",
        "System_4_50": "新增",
        "System_4_60": "",
        "System_4_70": "",
        "System_4_80": "1",
        "System_4_90": "",
        "System_4_100": "",
        "System_4_110": "",
        "typecode2": null,
        "typecode1": null,
        "obj2": null,
        "obj1": null
      },
      {
        "System_4_10": 6,
        "System_4_20": "005002",
        "System_4_30": "005",
        "System_4_40": "在库",
        "System_4_50": "在库",
        "System_4_60": "",
        "System_4_70": "",
        "System_4_80": "2",
        "System_4_90": "",
        "System_4_100": "",
        "System_4_110": "",
        "typecode2": null,
        "typecode1": null,
        "obj2": null,
        "obj1": null
      },
      {
        "System_4_10": 7,
        "System_4_20": "005003",
        "System_4_30": "005",
        "System_4_40": "出库",
        "System_4_50": "出库",
        "System_4_60": "",
        "System_4_70": "",
        "System_4_80": "3",
        "System_4_90": "",
        "System_4_100": "",
        "System_4_110": "",
        "typecode2": null,
        "typecode1": null,
        "obj2": null,
        "obj1": null
      }
    ],
    "codeId": "system_4",
    "DataValueField": "System_4_20",
    "DataTextField": "System_4_40"
  },
  {
    "DataSource": [
      {
        "ASSET_A5_AUTOID": 1,
        "ASSET_A5_ISDEL": null,
        "ASSET_A5_MAKETIME": null,
        "ASSET_A5_MAKEUSER": null,
        "ASSET_A5_PARENTID": null,
        "ASSET_A5_MAKEFROM": "1",
        "ASSET_A5_10": "财务部仓库",
        "ASSET_A5_20": "001",
        "ASSET_A5_30": "",
        "ASSET_A5_40": null,
        "ASSET_A5_50": null,
        "ASSET_A5_60": null,
        "ASSET_A5_70": null
      },
      {
        "ASSET_A5_AUTOID": 2,
        "ASSET_A5_ISDEL": null,
        "ASSET_A5_MAKETIME": null,
        "ASSET_A5_MAKEUSER": null,
        "ASSET_A5_PARENTID": null,
        "ASSET_A5_MAKEFROM": "1",
        "ASSET_A5_10": "临时仓",
        "ASSET_A5_20": "002",
        "ASSET_A5_30": "",
        "ASSET_A5_40": null,
        "ASSET_A5_50": null,
        "ASSET_A5_60": null,
        "ASSET_A5_70": null
      },
      {
        "ASSET_A5_AUTOID": 3,
        "ASSET_A5_ISDEL": null,
        "ASSET_A5_MAKETIME": null,
        "ASSET_A5_MAKEUSER": null,
        "ASSET_A5_PARENTID": null,
        "ASSET_A5_MAKEFROM": "1",
        "ASSET_A5_10": "地下仓库",
        "ASSET_A5_20": "003",
        "ASSET_A5_30": "地下三层",
        "ASSET_A5_40": null,
        "ASSET_A5_50": null,
        "ASSET_A5_60": null,
        "ASSET_A5_70": null
      }
    ],
    "codeId": "asset_a5",
    "DataValueField": "ASSET_A5_AUTOID",
    "DataTextField": "ASSET_A5_10"
  },
  {
    "DataSource": [
      {
        "ASSET_A3_AUTOID": 1,
        "ASSET_A3_ISDEL": null,
        "ASSET_A3_MAKETIME": null,
        "ASSET_A3_MAKEUSER": null,
        "ASSET_A3_PARENTID": null,
        "ASSET_A3_MAKEFROM": "1",
        "ASSET_A3_10": "东芝",
        "ASSET_A3_20": "01",
        "ASSET_A3_30": "东芝",
        "ASSET_A3_40": null,
        "ASSET_A3_50": null,
        "ASSET_A3_60": null,
        "ASSET_A3_70": null
      },
      {
        "ASSET_A3_AUTOID": 2,
        "ASSET_A3_ISDEL": null,
        "ASSET_A3_MAKETIME": null,
        "ASSET_A3_MAKEUSER": null,
        "ASSET_A3_PARENTID": null,
        "ASSET_A3_MAKEFROM": "1",
        "ASSET_A3_10": "戴尔",
        "ASSET_A3_20": "02",
        "ASSET_A3_30": "戴尔",
        "ASSET_A3_40": null,
        "ASSET_A3_50": null,
        "ASSET_A3_60": null,
        "ASSET_A3_70": null
      },
      {
        "ASSET_A3_AUTOID": 3,
        "ASSET_A3_ISDEL": null,
        "ASSET_A3_MAKETIME": null,
        "ASSET_A3_MAKEUSER": null,
        "ASSET_A3_PARENTID": null,
        "ASSET_A3_MAKEFROM": "1",
        "ASSET_A3_10": "华硕",
        "ASSET_A3_20": "03",
        "ASSET_A3_30": "华硕",
        "ASSET_A3_40": null,
        "ASSET_A3_50": null,
        "ASSET_A3_60": null,
        "ASSET_A3_70": null
      },
      {
        "ASSET_A3_AUTOID": 4,
        "ASSET_A3_ISDEL": null,
        "ASSET_A3_MAKETIME": null,
        "ASSET_A3_MAKEUSER": null,
        "ASSET_A3_PARENTID": null,
        "ASSET_A3_MAKEFROM": "1",
        "ASSET_A3_10": "三星",
        "ASSET_A3_20": "04",
        "ASSET_A3_30": "三星",
        "ASSET_A3_40": null,
        "ASSET_A3_50": null,
        "ASSET_A3_60": null,
        "ASSET_A3_70": null
      },
      {
        "ASSET_A3_AUTOID": 5,
        "ASSET_A3_ISDEL": null,
        "ASSET_A3_MAKETIME": null,
        "ASSET_A3_MAKEUSER": null,
        "ASSET_A3_PARENTID": null,
        "ASSET_A3_MAKEFROM": "1",
        "ASSET_A3_10": "华为",
        "ASSET_A3_20": "05",
        "ASSET_A3_30": "华为",
        "ASSET_A3_40": null,
        "ASSET_A3_50": null,
        "ASSET_A3_60": null,
        "ASSET_A3_70": null
      },
      {
        "ASSET_A3_AUTOID": 6,
        "ASSET_A3_ISDEL": null,
        "ASSET_A3_MAKETIME": null,
        "ASSET_A3_MAKEUSER": null,
        "ASSET_A3_PARENTID": null,
        "ASSET_A3_MAKEFROM": "1",
        "ASSET_A3_10": "小米",
        "ASSET_A3_20": "06",
        "ASSET_A3_30": "小米",
        "ASSET_A3_40": null,
        "ASSET_A3_50": null,
        "ASSET_A3_60": null,
        "ASSET_A3_70": null
      },
      {
        "ASSET_A3_AUTOID": 7,
        "ASSET_A3_ISDEL": null,
        "ASSET_A3_MAKETIME": null,
        "ASSET_A3_MAKEUSER": null,
        "ASSET_A3_PARENTID": null,
        "ASSET_A3_MAKEFROM": "1",
        "ASSET_A3_10": "苹果",
        "ASSET_A3_20": "07",
        "ASSET_A3_30": "苹果",
        "ASSET_A3_40": null,
        "ASSET_A3_50": null,
        "ASSET_A3_60": null,
        "ASSET_A3_70": null
      }
    ],
    "codeId": "asset_a3",
    "DataValueField": "ASSET_A3_AUTOID",
    "DataTextField": "ASSET_A3_10"
  },
  {
    "DataSource": [
      {
        "ASSET_A4_AUTOID": 10,
        "ASSET_A4_ISDEL": null,
        "ASSET_A4_MAKETIME": null,
        "ASSET_A4_MAKEUSER": null,
        "ASSET_A4_PARENTID": null,
        "ASSET_A4_MAKEFROM": "1",
        "ASSET_A4_10": "戴尔-型号1",
        "ASSET_A4_20": "12",
        "ASSET_A4_30": 2,
        "ASSET_A4_40": null,
        "ASSET_A4_50": null,
        "ASSET_A4_60": null,
        "ASSET_A4_70": null,
        "disabled": null
      },
      {
        "ASSET_A4_AUTOID": 14,
        "ASSET_A4_ISDEL": null,
        "ASSET_A4_MAKETIME": null,
        "ASSET_A4_MAKEUSER": null,
        "ASSET_A4_PARENTID": null,
        "ASSET_A4_MAKEFROM": "1",
        "ASSET_A4_10": "戴尔-型号2",
        "ASSET_A4_20": "45",
        "ASSET_A4_30": 2,
        "ASSET_A4_40": null,
        "ASSET_A4_50": null,
        "ASSET_A4_60": null,
        "ASSET_A4_70": null,
        "disabled": null
      },
      {
        "ASSET_A4_AUTOID": 15,
        "ASSET_A4_ISDEL": null,
        "ASSET_A4_MAKETIME": null,
        "ASSET_A4_MAKEUSER": null,
        "ASSET_A4_PARENTID": null,
        "ASSET_A4_MAKEFROM": "1",
        "ASSET_A4_10": "东芝-型号1",
        "ASSET_A4_20": "234",
        "ASSET_A4_30": 1,
        "ASSET_A4_40": null,
        "ASSET_A4_50": null,
        "ASSET_A4_60": null,
        "ASSET_A4_70": null,
        "disabled": null
      },
      {
        "ASSET_A4_AUTOID": 16,
        "ASSET_A4_ISDEL": null,
        "ASSET_A4_MAKETIME": null,
        "ASSET_A4_MAKEUSER": null,
        "ASSET_A4_PARENTID": null,
        "ASSET_A4_MAKEFROM": "1",
        "ASSET_A4_10": "东芝-型号2",
        "ASSET_A4_20": "34",
        "ASSET_A4_30": 1,
        "ASSET_A4_40": null,
        "ASSET_A4_50": null,
        "ASSET_A4_60": null,
        "ASSET_A4_70": null,
        "disabled": null
      },
      {
        "ASSET_A4_AUTOID": 1,
        "ASSET_A4_ISDEL": null,
        "ASSET_A4_MAKETIME": null,
        "ASSET_A4_MAKEUSER": null,
        "ASSET_A4_PARENTID": null,
        "ASSET_A4_MAKEFROM": null,
        "ASSET_A4_10": "东芝",
        "ASSET_A4_20": null,
        "ASSET_A4_30": null,
        "ASSET_A4_40": null,
        "ASSET_A4_50": null,
        "ASSET_A4_60": null,
        "ASSET_A4_70": null,
        "disabled": "1"
      },
      {
        "ASSET_A4_AUTOID": 2,
        "ASSET_A4_ISDEL": null,
        "ASSET_A4_MAKETIME": null,
        "ASSET_A4_MAKEUSER": null,
        "ASSET_A4_PARENTID": null,
        "ASSET_A4_MAKEFROM": null,
        "ASSET_A4_10": "戴尔",
        "ASSET_A4_20": null,
        "ASSET_A4_30": null,
        "ASSET_A4_40": null,
        "ASSET_A4_50": null,
        "ASSET_A4_60": null,
        "ASSET_A4_70": null,
        "disabled": "1"
      },
      {
        "ASSET_A4_AUTOID": 3,
        "ASSET_A4_ISDEL": null,
        "ASSET_A4_MAKETIME": null,
        "ASSET_A4_MAKEUSER": null,
        "ASSET_A4_PARENTID": null,
        "ASSET_A4_MAKEFROM": null,
        "ASSET_A4_10": "华硕",
        "ASSET_A4_20": null,
        "ASSET_A4_30": null,
        "ASSET_A4_40": null,
        "ASSET_A4_50": null,
        "ASSET_A4_60": null,
        "ASSET_A4_70": null,
        "disabled": "1"
      },
      {
        "ASSET_A4_AUTOID": 4,
        "ASSET_A4_ISDEL": null,
        "ASSET_A4_MAKETIME": null,
        "ASSET_A4_MAKEUSER": null,
        "ASSET_A4_PARENTID": null,
        "ASSET_A4_MAKEFROM": null,
        "ASSET_A4_10": "三星",
        "ASSET_A4_20": null,
        "ASSET_A4_30": null,
        "ASSET_A4_40": null,
        "ASSET_A4_50": null,
        "ASSET_A4_60": null,
        "ASSET_A4_70": null,
        "disabled": "1"
      },
      {
        "ASSET_A4_AUTOID": 5,
        "ASSET_A4_ISDEL": null,
        "ASSET_A4_MAKETIME": null,
        "ASSET_A4_MAKEUSER": null,
        "ASSET_A4_PARENTID": null,
        "ASSET_A4_MAKEFROM": null,
        "ASSET_A4_10": "华为",
        "ASSET_A4_20": null,
        "ASSET_A4_30": null,
        "ASSET_A4_40": null,
        "ASSET_A4_50": null,
        "ASSET_A4_60": null,
        "ASSET_A4_70": null,
        "disabled": "1"
      },
      {
        "ASSET_A4_AUTOID": 6,
        "ASSET_A4_ISDEL": null,
        "ASSET_A4_MAKETIME": null,
        "ASSET_A4_MAKEUSER": null,
        "ASSET_A4_PARENTID": null,
        "ASSET_A4_MAKEFROM": null,
        "ASSET_A4_10": "小米",
        "ASSET_A4_20": null,
        "ASSET_A4_30": null,
        "ASSET_A4_40": null,
        "ASSET_A4_50": null,
        "ASSET_A4_60": null,
        "ASSET_A4_70": null,
        "disabled": "1"
      },
      {
        "ASSET_A4_AUTOID": 7,
        "ASSET_A4_ISDEL": null,
        "ASSET_A4_MAKETIME": null,
        "ASSET_A4_MAKEUSER": null,
        "ASSET_A4_PARENTID": null,
        "ASSET_A4_MAKEFROM": null,
        "ASSET_A4_10": "苹果",
        "ASSET_A4_20": null,
        "ASSET_A4_30": null,
        "ASSET_A4_40": null,
        "ASSET_A4_50": null,
        "ASSET_A4_60": null,
        "ASSET_A4_70": null,
        "disabled": "1"
      }
    ],
    "codeId": "asset_a4",
    "DataValueField": "ASSET_A4_AUTOID",
    "DataTextField": "ASSET_A4_10",
    "TreeLevelField": "ASSET_A4_30",
    "DisabledField": "canselect"
  },
  {
    "DataSource": [
      {
        "System_2_10": 1,
        "System_2_20": "01",
        "System_2_30": "公司总部",
        "System_2_40": null,
        "System_2_50": null,
        "System_2_60": "1",
        "System_2_70": null,
        "System_2_80": null,
        "System_2_90": null,
        "System_2_100": "0",
        "System_2_110": "2",
        "System_2_120": null,
        "System_2_130": null,
        "System_2_140": null,
        "System_2_150": null,
        "System_2_160": null,
        "System_2_170": null,
        "System_2_180": null,
        "System_2_190": null,
        "System_9990": "1/1/01 12:00:00 AM",
        "System_9991": null,
        "System_9992": null,
        "System_9993": null,
        "System_9994": null,
        "System_9995": null
      },
      {
        "System_2_10": 2,
        "System_2_20": "2",
        "System_2_30": "财务部",
        "System_2_40": null,
        "System_2_50": null,
        "System_2_60": null,
        "System_2_70": "1",
        "System_2_80": null,
        "System_2_90": null,
        "System_2_100": null,
        "System_2_110": "老李",
        "System_2_120": null,
        "System_2_130": null,
        "System_2_140": null,
        "System_2_150": null,
        "System_2_160": null,
        "System_2_170": null,
        "System_2_180": null,
        "System_2_190": null,
        "System_9990": "0001/1/1 0:00:00",
        "System_9991": null,
        "System_9992": null,
        "System_9993": null,
        "System_9994": null,
        "System_9995": null
      },
      {
        "System_2_10": 3,
        "System_2_20": "3",
        "System_2_30": "运维部",
        "System_2_40": null,
        "System_2_50": null,
        "System_2_60": null,
        "System_2_70": "1",
        "System_2_80": null,
        "System_2_90": null,
        "System_2_100": null,
        "System_2_110": "老没",
        "System_2_120": null,
        "System_2_130": null,
        "System_2_140": null,
        "System_2_150": null,
        "System_2_160": null,
        "System_2_170": null,
        "System_2_180": null,
        "System_2_190": null,
        "System_9990": "0001/1/1 0:00:00",
        "System_9991": null,
        "System_9992": null,
        "System_9993": null,
        "System_9994": null,
        "System_9995": null
      },
      {
        "System_2_10": 4,
        "System_2_20": "4",
        "System_2_30": "销售部",
        "System_2_40": null,
        "System_2_50": null,
        "System_2_60": null,
        "System_2_70": "1",
        "System_2_80": null,
        "System_2_90": null,
        "System_2_100": null,
        "System_2_110": "老日",
        "System_2_120": null,
        "System_2_130": null,
        "System_2_140": null,
        "System_2_150": null,
        "System_2_160": null,
        "System_2_170": null,
        "System_2_180": null,
        "System_2_190": null,
        "System_9990": "0001/1/1 0:00:00",
        "System_9991": null,
        "System_9992": null,
        "System_9993": null,
        "System_9994": null,
        "System_9995": null
      },
      {
        "System_2_10": 5,
        "System_2_20": "8",
        "System_2_30": "研发部",
        "System_2_40": null,
        "System_2_50": null,
        "System_2_60": null,
        "System_2_70": "1",
        "System_2_80": null,
        "System_2_90": null,
        "System_2_100": null,
        "System_2_110": "8",
        "System_2_120": null,
        "System_2_130": null,
        "System_2_140": null,
        "System_2_150": null,
        "System_2_160": null,
        "System_2_170": null,
        "System_2_180": null,
        "System_2_190": null,
        "System_9990": "0001-01-01 00:00:00",
        "System_9991": null,
        "System_9992": null,
        "System_9993": null,
        "System_9994": null,
        "System_9995": null
      },
      {
        "System_2_10": 6,
        "System_2_20": "9",
        "System_2_30": "对外工程部",
        "System_2_40": null,
        "System_2_50": null,
        "System_2_60": null,
        "System_2_70": "1",
        "System_2_80": null,
        "System_2_90": null,
        "System_2_100": null,
        "System_2_110": "9",
        "System_2_120": null,
        "System_2_130": null,
        "System_2_140": null,
        "System_2_150": null,
        "System_2_160": null,
        "System_2_170": null,
        "System_2_180": null,
        "System_2_190": null,
        "System_9990": "0001-01-01 00:00:00",
        "System_9991": null,
        "System_9992": null,
        "System_9993": null,
        "System_9994": null,
        "System_9995": null
      },
      {
        "System_2_10": 7,
        "System_2_20": "5",
        "System_2_30": "交付部",
        "System_2_40": null,
        "System_2_50": null,
        "System_2_60": null,
        "System_2_70": "1",
        "System_2_80": null,
        "System_2_90": null,
        "System_2_100": null,
        "System_2_110": "5",
        "System_2_120": null,
        "System_2_130": null,
        "System_2_140": null,
        "System_2_150": null,
        "System_2_160": null,
        "System_2_170": null,
        "System_2_180": null,
        "System_2_190": null,
        "System_9990": "0001-01-01 00:00:00",
        "System_9991": null,
        "System_9992": null,
        "System_9993": null,
        "System_9994": null,
        "System_9995": null
      },
      {
        "System_2_10": 8,
        "System_2_20": "11",
        "System_2_30": "商务部",
        "System_2_40": null,
        "System_2_50": null,
        "System_2_60": null,
        "System_2_70": "1",
        "System_2_80": null,
        "System_2_90": null,
        "System_2_100": null,
        "System_2_110": "11",
        "System_2_120": null,
        "System_2_130": null,
        "System_2_140": null,
        "System_2_150": null,
        "System_2_160": null,
        "System_2_170": null,
        "System_2_180": null,
        "System_2_190": null,
        "System_9990": "0001-01-01 00:00:00",
        "System_9991": null,
        "System_9992": null,
        "System_9993": null,
        "System_9994": null,
        "System_9995": null
      }
    ],
    "codeId": "system_2",
    "DataValueField": "System_2_10",
    "DataTextField": "System_2_30"
  }
]